### ISSUE TITLE
ObjectDisposedException in Android renderer

### ISSUE THREAD

**Issue by SamuelDebruyn** [XAM-Consulting/SlideOverKit#13]
One of my apps crashed with the following stack trace which I suppose is caused by a bug in the SlideOverKit renderer on Android:

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SlideOverKit.Droid.MenuContainerPageDroidRenderer'.
  at Java.Interop.JniPeerMembers.AssertSelf (IJavaPeerable self) <0xae7123d8 + 0x000a4> in <filename unknown>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) <0xae712200 + 0x00023> in <filename unknown>:0 
  at Android.Views.ViewGroup.RemoveView (Android.Views.View view) <0x96328f90 + 0x0014b> in <filename unknown>:0 
  at SlideOverKit.Droid.SlideOverKitDroidHandler.HideBackgroundOverlay () <0x96f5f3d0 + 0x0002f> in <filename unknown>:0 
  at SlideOverKit.Droid.SlideOverKitDroidHandler.<AddMenu>b__13_2 (Boolean open, Double alpha) <0x96f5f330 + 0x0004b> in <filename unknown>:0 
  at SlideOverKit.Droid.AnimatorListener.OnAnimationEnd (Android.Animation.Animator animation) <0x96331ee0 + 0x000bf> in <filename unknown>:0 
  at Android.Animation.Animator+IAnimatorListenerInvoker.n_OnAnimationEnd_Landroid_animation_Animator_ (IntPtr jnienv, IntPtr native__this, IntPtr native_animation) <0x9632f770 + 0x00063> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:a48f1c7d-b4fd-45ed-9e0b-87f33ad2714a (intptr,intptr,intptr)
	at md56e02c46cd6f48bbbdd10f5c711319921.AnimatorListener.n_onAnimationEnd(Native Method)
	at md56e02c46cd6f48bbbdd10f5c711319921.AnimatorListener.onAnimationEnd(AnimatorListener.java:41)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1116)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
	at android.view.Choreographer.doCallbacks(Choreographer.java:596)
	at android.view.Choreographer.doFrame(Choreographer.java:556)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5696)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by jessejiang0214** [comment]
Fixed c3a78122483d38c51665306b4f2835911fb8e447
